// Code generated by goctl. DO NOT EDIT.
package types

type JwtAuth struct {
}

type UserLoginReq struct {
	UserName string `json:"userName"`
	UserPass string `json:"userPass"`
}

type UserLoginRes struct {
	Token string `json:"token"` // jwtToken
}

type UserRegisterReq struct {
	Avatar   string `json:"avatar"`
	UserName string `json:"userName"`
	UserPass string `json:"userPass"`
	NickName string `json:"nickName"`
	Gender   int64  `json:"gender,options=[1,2]"` // 1为男 2为女
	Age      int64  `json:"age,range=(0:100)"`
	DeviceId string `json:"deviceId"`
}
